include:
  - ./docker-compose-loki.yml

services:
  complexity-ai:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "2999:2999"
    networks:
      - loki  # From ./docker-compose-loki.yml